package com.ljc.socialdemo.db;

import com.ljc.socialdemo.db.dao.Message;
import com.ljc.socialdemo.db.dao.Notification;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by 18075 on 2018/11/9.
 */

public class TestDao2 {
    public static List<Notification> getNotificationList() {
        List list = new ArrayList();
        list.add( new Notification(null,"[通知]#维多利亚的秘密秀# 维密秀高清图曝光 这是海胆精和床单天使吧"));
        list.add( new Notification(null,"[通知]网曝江西#万人品柚活动遭哄抢# 当地农业局回应称商家损失不大"));
        list.add( new Notification(null,"[通知]唐砖》开头太甜结局太虐，网友：宁愿被甜死也不要被虐死"));
        list.add( new Notification(null,"[通知]亳州一学生迟到两分钟遭老师殴打，四把扫把都打断！"));
        list.add( new Notification(null,"[通知]孟山都Monsanto与美国政府/官员的关系"));
        list.add( new Notification(null,"[通知]外媒：沙特又一名记者因揭露王室违法行为惨遭杀害"));
        list.add( new Notification(null,"[通知]五分钟教你看懂2018年美国中期选举"));
        list.add( new Notification(null,"[通知]五分钟教你看懂2018年美国中期选举"));
        list.add( new Notification(null,"[通知]父子拔枪互射致儿子死亡，这场惨剧起因竟是……"));
        list.add( new Notification(null,"[通知]一身粉白+双马尾辫，装16岁少女招摇撞骗！竟有几万人信了"));
        list.add( new Notification(null,"[通知]剥离文旅集团后 王健林再投300亿建万达城"));
        list.add( new Notification(null,"[通知]40年40个瞬间| 家庭联产承包"));
        list.add( new Notification(null,"[通知]守望先锋个人脑洞：守望先锋故事背后一切的真相PART:2"));
        list.add( new Notification(null,"[通知]中国股市最大的神棍和骗子---李大霄"));
        list.add( new Notification(null,"[通知]《延禧攻略2》将开拍，女主从魏璎珞换成了她，网友：熬夜也追"));
        list.add( new Notification(null,"[通知]我们用了一百年，终于能够一起坐下来谈谈航空发动机了"));
        list.add( new Notification(null,"[通知]合肥一楼盘每平米降六千被约谈 专家：市场行为应得到监管部门支持"));
        list.add( new Notification(null,"[通知]手相算命：从手指长度看你是什么命格"));
        list.add( new Notification(null,"[通知]“女网友”承认是骗子，小伙：没事，只要跟我好好过日子"));
        list.add( new Notification(null,"[通知]代答苏占军十问传媒大学"));
        list.add( new Notification(null,"[通知]只奢望给予他一份最最基本的安全保障？足矣 。"));
        list.add( new Notification(null,"[通知]关于猎人集训队的那些鸡毛蒜皮的事！"));
        list.add( new Notification(null,"[通知]12 生肖 +12 星座 ＝ 超准的潜在性格分析！"));
        list.add( new Notification(null,"[通知]明星们开在深圳的餐厅，一般人都不知道！"));
        list.add( new Notification(null,"[通知]炎亚纶上热搜复活了“东纶”CP，飞轮海不愧是宝藏男团"));
        list.add( new Notification(null,"[通知]《千与千寻》：细思恐极，原来当年好多剧情都没看懂"));
        list.add( new Notification(null,"[通知]恶意传播艾滋病，这些人渣究竟是什么心理？"));
        list.add( new Notification(null,"[通知]29岁霉霉流行乐坛无敌手，一张图让你服"));
        list.add( new Notification(null,"[通知]（周运）克里斯汀每周星座运程11.8-11.14"));
        list.add( new Notification(null,"[通知]泉港碳九泄漏，谁在欲盖弥彰？"));
        list.add( new Notification(null,"[通知]十二星座11月9日运势：欢快周五，适合约会、聚会"));
        list.add( new Notification(null,"[通知]大学把成绩单寄给家长是教育的倒退和迷失"));
        list.add( new Notification(null,"[通知]IG夺冠后第一条好消息：rookie不再是韩援！LPL本土肉鸡明年上线"));
        list.add( new Notification(null,"[通知]炎亚纶男友B澄清，绯闻男友冒泡了"));
        list.add( new Notification(null,"[通知]广场舞大妈争地盘，不惜用铲车铲走停在停车位上的小轿车。"));
        list.add( new Notification(null,"[通知]怀抱婴儿女子拿小石头扔击女童头部，又伪装目击者上前安慰"));
        list.add( new Notification(null,"[通知]25岁自贡患病小伙咨询捐献眼角膜，医生为他求助：这非绝症"));
        list.add( new Notification(null,"[通知]有空来桔钓沙，拥抱阳光沙滩和海浪"));
        list.add( new Notification(null,"[通知]炎亚纶男友B澄清，表示还很爱他，时间线一梳理，才发现另有玄机"));
        list.add( new Notification(null,"[通知]线下零售将死？雷军：不存在"));
        list.add( new Notification(null,"[通知]西安“小香港”要被拆了？隐藏于此的美食可先得尝尝"));
        list.add( new Notification(null,"[通知]西安“小香港”要被拆了？隐藏于此的美食可先得尝尝"));
        list.add( new Notification(null,"[通知]哈佛医学院：压力大可致脑萎缩！身体8个表现早提醒过你了"));
        list.add( new Notification(null,"[通知]现在多少钱才抵得过30年前的“万元户”，看完心情不能平复~"));
        list.add( new Notification(null,"[通知]女儿，为什么我不让你嫁给穷小子？"));
        list.add( new Notification(null,"[通知]转：6岁，19岁，28岁，38岁，47岁，你被几岁的俞飞鸿惊艳到了？"));
        list.add( new Notification(null,"[通知]《创业时代》剧情有点扯？近几年扯到天边的国产剧多了去了！"));
        list.add( new Notification(null,"[通知]朋友圈都在传她的照片！有人送房送车“卖女儿”，唯一要求竟是…爸妈..."));
        list.add( new Notification(null,"[通知]成都：胆敢辱骂袭击公交司机，第一时间出警从快严惩"));
        list.add( new Notification(null,"[通知]《光明时报》评论：泉港碳九泄露，事实不该成谜"));
        list.add( new Notification(null,"[通知]立冬了，看下这篇就温暖了"));
        list.add( new Notification(null,"[通知]唐嫣 婚礼最难忘瞬间 很感动"));
        list.add( new Notification(null,"[通知]【Long range】西格绍尔SIG 716步枪图集"));
        list.add( new Notification(null,"[通知]IG夺冠了，LOL官方却挨喷了"));
        list.add( new Notification(null,"[通知]【AUG改型】澳大利亚军队EF88自动步枪图集"));
        list.add( new Notification(null,"[通知]刘昊然 裤腿藏酒 男生的自拍方式"));
        list.add( new Notification(null,"[通知]新疆旅游攻略之赛里木湖"));
        list.add( new Notification(null,"[通知]中日关系面临考验：日本再出“险招”，瞄准钓鱼岛搞事"));
        list.add( new Notification(null,"[通知]中学生为何不爱上体育课"));
        list.add( new Notification(null,"[通知]经常让人大跌眼镜却毫不自知的星座"));
        list.add( new Notification(null,"[通知]带这样的衣帽间，才能搞定挑剔的女人！"));
        list.add( new Notification(null,"[通知]公交司售揭秘八条防盗“暗语”"));
        list.add( new Notification(null,"[通知]怒问：后妈带娃一周，“滑倒死”，脚趾缝里被扎针！不予立案？"));
        list.add( new Notification(null,"[通知]泰国女星Matt Peranee正式回应与富商Songkran宋干交谈事件始末"));
        list.add( new Notification(null,"[通知]突发！南京中央商场内一人坠楼身亡"));
        list.add( new Notification(null,"[通知]还有人分不清什么是黑社会，什么是恶势力？"));
        list.add( new Notification(null,"[通知]坚持中国共产党的领导 画好最大同心圆"));
        list.add( new Notification(null,"[通知]娱乐圈离不开刘海的5个男星，他们掀起头发的样子吓到我了！"));
        list.add( new Notification(null,"[通知]什么是真正放下一个人？拉黑？删除？"));
        list.add( new Notification(null,"[通知]光绪年间北京城，曾被八国联军炮击的朝阳门"));
        list.add( new Notification(null,"[通知]我的“00后”媒介记忆"));
        list.add( new Notification(null,"[通知]小户型装修必备技巧，不看后悔!"));
        list.add( new Notification(null,"[通知]这15项科技成果世界领先！华为芯片、小程序上榜"));
        list.add( new Notification(null,"[通知]师伟：论奴性"));
        list.add( new Notification(null,"[通知]完善制度从严约束 坚决纠正停牌不正之风"));
        list.add( new Notification(null,"[通知]6.97吨碳九泄露，危害会有多大？"));
        list.add( new Notification(null,"[通知]死去的妓院老板，胜利当选！"));
        list.add( new Notification(null,"[通知]福建泉港发生碳九泄露 专家释疑“碳九是什么”"));
        list.add( new Notification(null,"[通知]又一小学生作文走红：“可怜啊 每天才5毛零花钱”"));
        list.add( new Notification(null,"[通知]是什么让吴亦凡的新专成为了世界级的笑话？"));
        list.add( new Notification(null,"[通知]骑虎难下吴亦凡"));
        list.add( new Notification(null,"[通知]吵架段位最高的三个星座"));
        list.add( new Notification(null,"[通知]1991伊拉克战争的局中局"));
        list.add( new Notification(null,"[通知]冬天真的要来了！虽然超凶冷空气“超水”，但更凶的冷空气在酝酿"));
        list.add( new Notification(null,"[通知]今天过后，她们代表了美国政治的未来？"));
        list.add( new Notification(null,"[通知]炎亚纶机场视频 别再给他压力了"));
        list.add( new Notification(null,"[通知]人类史上真的有过「母系氏族」阶段吗｜大象公会"));
        list.add( new Notification(null,"[通知]飞轮海成员谁最累"));
        list.add( new Notification(null,"[通知]飞轮海成员谁最累 满满的回忆一组图"));
        list.add( new Notification(null,"[通知]吴佩慈否认纪晓波被抓 已正式起诉"));
        list.add( new Notification(null,"[通知]重庆公交车坠江事件后续：打人乘客家属求饶，“不要再砸了！"));
        list.add( new Notification(null,"[通知]中华烟哭了!小村子造20年假烟,造出上百亿美国市场,连正品都来抄袭"));
        list.add( new Notification(null,"[通知]公交事故警示录：小怒沉车，大怒乱国"));
        list.add( new Notification(null,"[通知]这是一场醒着的梦游"));
        list.add( new Notification(null,"[通知]（新月许愿）2018年11月8日天蝎座新月许愿指南"));
        list.add( new Notification(null,"[通知]林俊杰的MV曾因太重口而被禁播，胆小勿入"));
        list.add( new Notification(null,"[通知]世俗化忘了阶级 宗教化就是必然 ——巴列维时代的伊朗不值得赞美"));
        list.add( new Notification(null,"[通知]炎亚纶被曝劈腿三男之后细扒，好大一个瓜"));
        list.add( new Notification(null,"[通知]辰亦儒曾参加美少女选拔赛，原来飞轮海成员每一个都有故事!"));
        list.add( new Notification(null,"[通知]徐克，周星驰眼中的吴亦凡"));
        list.add( new Notification(null,"[通知]90后罕见癌症患者的生命抉择：无药可治的现实与试新药碰运气"));
        list.add( new Notification(null,"[通知]你有芯片，我有稀土"));
        list.add( new Notification(null,"[通知]炸裂！2018秋裤预警来了，秋裤即将覆盖8成国土"));
        list.add( new Notification(null,"[通知]法国人拍下1908年被破坏之前的敦煌莫高窟，极大视觉震撼！"));
        list.add( new Notification(null,"[通知]炎亚纶道歉，这是我朝首个正式出柜的当红艺人吧？不过蛮让人心疼！"));
        list.add( new Notification(null,"[通知]古代皇室如果生下双胞胎，皇家怎么对待，说出来你可能不信"));
        list.add( new Notification(null,"[通知]中华烟哭了!小村子造20年假烟,造出上百亿美国市场,连正品都来抄袭"));
        list.add( new Notification(null,"[通知]这沉默的爱，记蓝忘机的感情"));
        list.add( new Notification(null,"[通知]（周运）罗伯每周心灵指引11.7-11.13"));
        list.add( new Notification(null,"[通知]心疼！80 岁老太投奔亲戚遭嫌弃，连续几天淋雨挨冻"));
        list.add( new Notification(null,"[通知]成为一代名媛的一小步"));
        list.add( new Notification(null,"[通知]美国中期选举结果：民主党夺回众议院，共和党保住参议院"));
        list.add( new Notification(null,"[通知]林志玲被问单身如何解决生理问题, 五字凸显高情商, 不愧是女神"));
        list.add( new Notification(null,"[通知]十二星座11月8日运势：新月降临，木星移位，重要！"));
        list.add( new Notification(null,"[通知]郑元畅写给贺军翔的日记？假的"));
        list.add( new Notification(null,"[通知]三剧连播，“高级瘫”倪大红真大红了！明明很有人脉，却处处低调"));
        list.add( new Notification(null,"[通知]外媒文章：中俄“亲密”改变世界地缘政治"));
        list.add( new Notification(null,"[通知]40年代饥荒时候的照片，人们饿得啃树皮，村子里都没人住"));
        list.add( new Notification(null,"[通知]邓立群 | 毛主席：我们始终强调要按照十月革命的道路办事"));
        list.add( new Notification(null,"[通知]今天，小铁有几个重要的事情想跟大家说说！！"));
        list.add( new Notification(null,"[通知]走秀进博会 标致全新508 SW国内首发"));
        list.add( new Notification(null,"[通知]是谁害了吴亦凡？"));
        list.add( new Notification(null,"[通知]【彪悍大叔】各国军警特战图集"));
        list.add( new Notification(null,"[通知]动物画法200例！看完这篇干货帖！！！画动物不再是难事~~~"));
        list.add( new Notification(null,"[通知]张艺兴 北京时间11月7日美国纽约FAN EVENT 人气爆棚"));
        list.add( new Notification(null,"[通知]【魔幻风】战术版AK 完美的轻武器"));
        list.add( new Notification(null,"[通知]一女子因从事“法轮功”邪教活动在番禺获刑"));
        list.add( new Notification(null,"[通知]中国兵器震撼亮相珠海航展 展出四大领域新锐武器"));
        list.add( new Notification(null,"[通知]孩子的格局从灵活思维开始，三个方法从小做起来"));
        list.add( new Notification(null,"[通知]崔永元借安娜孩子的夭折，暗示还有大猛料，其实，他是陷入了两难境地"));
        list.add( new Notification(null,"[通知]“崔永元真面馆”火起来的真经"));
        list.add( new Notification(null,"[通知]多张他和其他翘屁嫩男的亲密照，还有他绝情分手的聊天记录曝光？"));
        list.add( new Notification(null,"[通知]昌平一村支书挪借1.5亿拆迁款收300万好处费！此前就曾因罪被判刑"));
        list.add( new Notification(null,"[通知]安妮-2018-2019：木星射手座行运的整体影响"));
        list.add( new Notification(null,"[通知]林宥嘉的《浪费》写的竟是炎亚纶汪东城的爱情故事 导致组合分裂"));

        return list;
    }

}
