package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ljc.socialdemo.db.dao.Commen;
import com.ljc.socialdemo.db.dao.Discove;
import com.ljc.socialdemo.db.dao.Message;
import com.ljc.socialdemo.db.dao.Notification;
import com.ljc.socialdemo.db.dao.User;
import com.ljc.socialdemo.db.dao.UserInfo;
import com.ljc.socialdemo.db.dao.Zan;

import greendao.CommenDao;
import greendao.DiscoveDao;
import greendao.MessageDao;
import greendao.NotificationDao;
import greendao.UserDao;
import greendao.UserInfoDao;
import greendao.ZanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commenDaoConfig;
    private final DaoConfig discoveDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig notificationDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig zanDaoConfig;

    private final CommenDao commenDao;
    private final DiscoveDao discoveDao;
    private final MessageDao messageDao;
    private final NotificationDao notificationDao;
    private final UserDao userDao;
    private final UserInfoDao userInfoDao;
    private final ZanDao zanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commenDaoConfig = daoConfigMap.get(CommenDao.class).clone();
        commenDaoConfig.initIdentityScope(type);

        discoveDaoConfig = daoConfigMap.get(DiscoveDao.class).clone();
        discoveDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        notificationDaoConfig = daoConfigMap.get(NotificationDao.class).clone();
        notificationDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        zanDaoConfig = daoConfigMap.get(ZanDao.class).clone();
        zanDaoConfig.initIdentityScope(type);

        commenDao = new CommenDao(commenDaoConfig, this);
        discoveDao = new DiscoveDao(discoveDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        notificationDao = new NotificationDao(notificationDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        zanDao = new ZanDao(zanDaoConfig, this);

        registerDao(Commen.class, commenDao);
        registerDao(Discove.class, discoveDao);
        registerDao(Message.class, messageDao);
        registerDao(Notification.class, notificationDao);
        registerDao(User.class, userDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(Zan.class, zanDao);
    }
    
    public void clear() {
        commenDaoConfig.clearIdentityScope();
        discoveDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        notificationDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        zanDaoConfig.clearIdentityScope();
    }

    public CommenDao getCommenDao() {
        return commenDao;
    }

    public DiscoveDao getDiscoveDao() {
        return discoveDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public NotificationDao getNotificationDao() {
        return notificationDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public ZanDao getZanDao() {
        return zanDao;
    }

}
